const fs=require('fs');
const r=JSON.parse(fs.readFileSync(process.argv[2],'utf8')); const a=r.audits;
const items=(k)=>((a[k]&&a[k].details&&a[k].details.items)||[]);
console.log('=== '+r.finalDisplayedUrl+' ===');
const lcpItems=items('largest-contentful-paint-element');
console.log('LCP element:', JSON.stringify(lcpItems[0]||{}).slice(0,420));
console.log('LCP phases:', JSON.stringify((lcpItems[1]||{}).items||[]));
console.log('--- bootup (script CPU) top ---');
for (const it of items('bootup-time').slice(0,12)) console.log(Math.round(it.total).toString().padStart(6),'ms  scripting',Math.round(it.scripting),'parse',Math.round(it.scriptParseCompile), String(it.url).replace(/^.*4174/,''));
console.log('--- main thread breakdown ---');
for (const it of items('mainthread-work-breakdown')) console.log(Math.round(it.duration).toString().padStart(6),'ms',it.groupLabel);
console.log('--- long tasks ---');
for (const it of items('long-tasks').slice(0,14)) console.log(Math.round(it.duration).toString().padStart(6),'ms @',Math.round(it.startTime), String(it.url||'').replace(/^.*4174/,''));
console.log('--- render blocking ---');
for (const it of items('render-blocking-resources')) console.log(Math.round(it.wastedMs),'ms',it.totalBytes,'B',String(it.url).replace(/^.*4174/,''));
console.log('--- unused JS (top) ---');
for (const it of items('unused-javascript').slice(0,8)) console.log(it.wastedBytes,'/',it.totalBytes,'B wasted',String(it.url).replace(/^.*4174/,''));
console.log('--- unused CSS ---');
for (const it of items('unused-css-rules').slice(0,5)) console.log(it.wastedBytes,'/',it.totalBytes,'B wasted',String(it.url).replace(/^.*4174/,''));
console.log('--- network top by transfer ---');
const net=items('network-requests').slice().sort((x,y)=>(y.transferSize||0)-(x.transferSize||0)).slice(0,24);
for (const it of net) console.log(String(it.transferSize).padStart(7),'B', String(it.resourceType||'').padEnd(10), 'start',Math.round(it.networkRequestTime||0),'end',Math.round(it.networkEndTime||0), String(it.url).replace(/^.*4174/,''));
console.log('--- dom size ---', JSON.stringify(items('dom-size').map(i=>i.value&&(i.value.value!==undefined?i.value.value:i.value))));
console.log('--- layout shifts ---', JSON.stringify(items('layout-shifts').slice(0,3)).slice(0,600));
