/*
 * СГЕНЕРИРОВАННЫЙ ФАЙЛ. Не править руками.
 * Источник: scripts/font-library.manifest.js
 * Пересборка: node scripts/build-font-library.js
 */

export type ContentFontCategory = 'sans' | 'serif' | 'handwritten' | 'display' | 'mono';
export type ContentFontSource = 'system' | 'hero' | 'library';
export type ContentFontWeight = 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900;

export type ContentFontDefinition = {
  id: string;
  label: string;
  cssFamily: string;
  category: ContentFontCategory;
  source: ContentFontSource;
  bodySafe: boolean;
  weights: readonly ContentFontWeight[];
  description: string;
};

/**
 * Первые две записи не скачиваются: `auto` отдаёт типографику самой страницы,
 * Inter приходит переменным шрифтом из пакета @fontsource-variable/inter.
 */
export const CONTENT_FONT_CATALOG = [
  {
    id: 'auto',
    label: "Авто · стиль сайта",
    cssFamily: '',
    category: 'sans',
    source: 'system',
    bodySafe: true,
    weights: [300, 400, 500, 600, 700, 800],
    description: 'Текущий шрифт и настройки выбранной страницы.',
  },
  {
    id: 'inter',
    label: "Inter",
    cssFamily: '"Inter Variable"',
    category: 'sans',
    source: 'system',
    bodySafe: true,
    weights: [300, 400, 500, 600, 700, 800],
    description: 'Чистый универсальный гротеск для интерфейсов и длинного текста.',
  },
  {
    id: 'arsenal',
    label: "Arsenal",
    cssFamily: '"WW Arsenal"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 700],
    description: "Узкий гуманистический гротеск для компактной вёрстки.",
  },
  {
    id: 'comfortaa',
    label: "Comfortaa",
    cssFamily: '"WW Comfortaa"',
    category: 'sans',
    source: 'library',
    bodySafe: false,
    weights: [400, 500, 700],
    description: "Круглый мягкий шрифт, уместен в лайфстайл-темах.",
  },
  {
    id: 'commissioner',
    label: "Commissioner",
    cssFamily: '"WW Commissioner"',
    category: 'sans',
    source: 'hero',
    bodySafe: true,
    weights: [300, 400, 500, 600, 700],
    description: "Гибкий деловой гротеск с хорошей кириллицей.",
  },
  {
    id: 'cuprum',
    label: "Cuprum",
    cssFamily: '"WW Cuprum"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Узкий шрифт с индустриальным характером.",
  },
  {
    id: 'exo-2',
    label: "Exo 2",
    cssFamily: '"WW Exo 2"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700, 800],
    description: "Техно-гротеск с наклонными срезами для digital-тем.",
  },
  {
    id: 'fira-sans',
    label: "Fira Sans",
    cssFamily: '"WW Fira Sans"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Инженерный гротеск, спокойный в длинном тексте.",
  },
  {
    id: 'geologica',
    label: "Geologica",
    cssFamily: '"WW Geologica"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Характерный геометрический гротеск для UI и текста.",
  },
  {
    id: 'golos-text',
    label: "Golos Text",
    cssFamily: '"WW Golos Text"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Очень читаемый шрифт, спроектированный для кириллицы.",
  },
  {
    id: 'jost',
    label: "Jost",
    cssFamily: '"WW Jost"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Геометрика в духе Futura: сухо и по-дизайнерски.",
  },
  {
    id: 'manrope',
    label: "Manrope",
    cssFamily: '"WW Manrope"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700, 800],
    description: "Чистый геометрический гротеск для интерфейса и контента.",
  },
  {
    id: 'montserrat',
    label: "Montserrat",
    cssFamily: '"WW Montserrat"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700, 800],
    description: "Городской геометрический гротеск, привычный по вывескам.",
  },
  {
    id: 'nunito',
    label: "Nunito",
    cssFamily: '"WW Nunito"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 600, 700, 800],
    description: "Округлый дружелюбный гротеск без официоза.",
  },
  {
    id: 'nunito-sans',
    label: "Nunito Sans",
    cssFamily: '"WW Nunito Sans"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 600, 700],
    description: "Строгая версия Nunito для делового текста.",
  },
  {
    id: 'onest',
    label: "Onest",
    cssFamily: '"WW Onest"',
    category: 'sans',
    source: 'hero',
    bodySafe: true,
    weights: [400, 500, 600, 700],
    description: "Современный нейтральный гротеск для заголовков и текста.",
  },
  {
    id: 'open-sans',
    label: "Open Sans",
    cssFamily: '"WW Open Sans"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Спокойный рабочий гротеск, хорошо читается мелким кеглем.",
  },
  {
    id: 'oswald',
    label: "Oswald",
    cssFamily: '"WW Oswald"',
    category: 'sans',
    source: 'library',
    bodySafe: false,
    weights: [400, 500, 700],
    description: "Очень узкий плакатный гротеск для крупных заголовков.",
  },
  {
    id: 'play',
    label: "Play",
    cssFamily: '"WW Play"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 700],
    description: "Компактный техно-гротеск, хорош для цифр и метрик.",
  },
  {
    id: 'pt-sans',
    label: "PT Sans",
    cssFamily: '"WW PT Sans"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 700],
    description: "Государственный русский гротеск, безупречная кириллица.",
  },
  {
    id: 'pt-sans-narrow',
    label: "PT Sans Narrow",
    cssFamily: '"WW PT Sans Narrow"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 700],
    description: "Узкий PT Sans для плотных заголовков и таблиц.",
  },
  {
    id: 'raleway',
    label: "Raleway",
    cssFamily: '"WW Raleway"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700, 800],
    description: "Элегантный гротеск с характерной буквой W.",
  },
  {
    id: 'roboto',
    label: "Roboto",
    cssFamily: '"WW Roboto"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [300, 400, 500, 700],
    description: "Стандартный экранный гротеск Android, максимально нейтральный.",
  },
  {
    id: 'roboto-condensed',
    label: "Roboto Condensed",
    cssFamily: '"WW Roboto Condensed"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Узкий Roboto: помещает длинный заголовок в одну строку.",
  },
  {
    id: 'rubik',
    label: "Rubik",
    cssFamily: '"WW Rubik"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Гротеск со скруглёнными углами, заметный, но спокойный.",
  },
  {
    id: 'russo-one',
    label: "Russo One",
    cssFamily: '"WW Russo One"',
    category: 'sans',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Тяжёлый широкий шрифт для коротких лозунгов.",
  },
  {
    id: 'scada',
    label: "Scada",
    cssFamily: '"WW Scada"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 700],
    description: "Утилитарный гротеск для интерфейсных подписей.",
  },
  {
    id: 'sofia-sans',
    label: "Sofia Sans",
    cssFamily: '"WW Sofia Sans"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700, 800],
    description: "Мягкий современный гротеск для заголовков и текста.",
  },
  {
    id: 'tektur',
    label: "Tektur",
    cssFamily: '"WW Tektur"',
    category: 'sans',
    source: 'library',
    bodySafe: false,
    weights: [400, 500, 700],
    description: "Квадратный техничный шрифт с явным характером.",
  },
  {
    id: 'ubuntu',
    label: "Ubuntu",
    cssFamily: '"WW Ubuntu"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [300, 400, 500, 700],
    description: "Тёплый технологичный гротеск с мягкими окончаниями.",
  },
  {
    id: 'wix-madefor-display',
    label: "Wix Madefor Display",
    cssFamily: '"WW Wix Madefor Display"',
    category: 'sans',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700, 800],
    description: "Плотный современный гротеск для витринных заголовков.",
  },
  {
    id: 'alegreya',
    label: "Alegreya",
    cssFamily: '"WW Alegreya"',
    category: 'serif',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Литературная антиква с живым ритмом строки.",
  },
  {
    id: 'alice',
    label: "Alice",
    cssFamily: '"WW Alice"',
    category: 'serif',
    source: 'library',
    bodySafe: true,
    weights: [400],
    description: "Мягкая книжная антиква с лёгким винтажным оттенком.",
  },
  {
    id: 'bitter',
    label: "Bitter",
    cssFamily: '"WW Bitter"',
    category: 'serif',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Брусковая антиква, уверенно держит мелкий кегль.",
  },
  {
    id: 'eb-garamond',
    label: "EB Garamond",
    cssFamily: '"WW EB Garamond"',
    category: 'serif',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Ренессансная антиква с тонким классическим рисунком.",
  },
  {
    id: 'kurale',
    label: "Kurale",
    cssFamily: '"WW Kurale"',
    category: 'serif',
    source: 'library',
    bodySafe: true,
    weights: [400],
    description: "Антиква с лёгким рукописным наклоном штриха.",
  },
  {
    id: 'ledger',
    label: "Ledger",
    cssFamily: '"WW Ledger"',
    category: 'serif',
    source: 'library',
    bodySafe: true,
    weights: [400],
    description: "Строгая контрастная антиква с деловым тоном.",
  },
  {
    id: 'literata',
    label: "Literata",
    cssFamily: '"WW Literata"',
    category: 'serif',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Книжная антиква Google Books, сделана для чтения с экрана.",
  },
  {
    id: 'lora',
    label: "Lora",
    cssFamily: '"WW Lora"',
    category: 'serif',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Современная антиква для спокойного редакционного текста.",
  },
  {
    id: 'merriweather',
    label: "Merriweather",
    cssFamily: '"WW Merriweather"',
    category: 'serif',
    source: 'library',
    bodySafe: true,
    weights: [400, 700],
    description: "Плотная антиква с крупным очком, хороша в статьях.",
  },
  {
    id: 'old-standard-tt',
    label: "Old Standard TT",
    cssFamily: '"WW Old Standard TT"',
    category: 'serif',
    source: 'library',
    bodySafe: true,
    weights: [400, 700],
    description: "Классическая книжная антиква с историческим характером.",
  },
  {
    id: 'podkova',
    label: "Podkova",
    cssFamily: '"WW Podkova"',
    category: 'serif',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Брусковая антиква с плотными засечками-подковами.",
  },
  {
    id: 'pt-serif',
    label: "PT Serif",
    cssFamily: '"WW PT Serif"',
    category: 'serif',
    source: 'library',
    bodySafe: true,
    weights: [400, 700],
    description: "Надёжная русская антиква для заголовков и длинного текста.",
  },
  {
    id: 'roboto-serif',
    label: "Roboto Serif",
    cssFamily: '"WW Roboto Serif"',
    category: 'serif',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Современная экранная антиква с уверенной кириллицей.",
  },
  {
    id: 'vollkorn',
    label: "Vollkorn",
    cssFamily: '"WW Vollkorn"',
    category: 'serif',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Тёплая антиква для человечного, неказённого тона.",
  },
  {
    id: 'anonymous-pro',
    label: "Anonymous Pro",
    cssFamily: '"WW Anonymous Pro"',
    category: 'mono',
    source: 'library',
    bodySafe: true,
    weights: [400, 700],
    description: "Моношрифт с ретро-терминальным характером.",
  },
  {
    id: 'cousine',
    label: "Cousine",
    cssFamily: '"WW Cousine"',
    category: 'mono',
    source: 'library',
    bodySafe: true,
    weights: [400, 700],
    description: "Метрика Courier New: самый «машинописный» из читаемых.",
  },
  {
    id: 'fira-code',
    label: "Fira Code",
    cssFamily: '"WW Fira Code"',
    category: 'mono',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Fira Mono с лигатурами, выглядит как редактор кода.",
  },
  {
    id: 'fira-mono',
    label: "Fira Mono",
    cssFamily: '"WW Fira Mono"',
    category: 'mono',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Спокойный инженерный моношрифт.",
  },
  {
    id: 'ibm-plex-mono',
    label: "IBM Plex Mono",
    cssFamily: '"WW IBM Plex Mono"',
    category: 'mono',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Технический моношрифт с характерными засечками.",
  },
  {
    id: 'jetbrains-mono',
    label: "JetBrains Mono",
    cssFamily: '"WW JetBrains Mono"',
    category: 'mono',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Моноширинный шрифт с крупным очком, читается издалека.",
  },
  {
    id: 'martian-mono',
    label: "Martian Mono",
    cssFamily: '"WW Martian Mono"',
    category: 'mono',
    source: 'library',
    bodySafe: false,
    weights: [400, 500, 700],
    description: "Широкий техно-моношрифт для крупных заголовков.",
  },
  {
    id: 'noto-sans-mono',
    label: "Noto Sans Mono",
    cssFamily: '"WW Noto Sans Mono"',
    category: 'mono',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Универсальный моношрифт с максимальным покрытием знаков.",
  },
  {
    id: 'pt-mono',
    label: "PT Mono",
    cssFamily: '"WW PT Mono"',
    category: 'mono',
    source: 'library',
    bodySafe: true,
    weights: [400],
    description: "Классическая печатная машинка: ровная моноширинная кириллица.",
  },
  {
    id: 'roboto-mono',
    label: "Roboto Mono",
    cssFamily: '"WW Roboto Mono"',
    category: 'mono',
    source: 'library',
    bodySafe: true,
    weights: [300, 400, 500, 700],
    description: "Нейтральный моношрифт для цифр, кода и таблиц.",
  },
  {
    id: 'source-code-pro',
    label: "Source Code Pro",
    cssFamily: '"WW Source Code Pro"',
    category: 'mono',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Аккуратный моношрифт Adobe с полной кириллицей.",
  },
  {
    id: 'ubuntu-sans-mono',
    label: "Ubuntu Sans Mono",
    cssFamily: '"WW Ubuntu Sans Mono"',
    category: 'mono',
    source: 'library',
    bodySafe: true,
    weights: [400, 500, 700],
    description: "Тёплый моношрифт со скруглёнными формами.",
  },
  {
    id: 'cormorant-garamond',
    label: "Cormorant Garamond",
    cssFamily: '"WW Cormorant Garamond"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400, 500, 700],
    description: "Выразительная антиква для премиальных заголовков.",
  },
  {
    id: 'forum',
    label: "Forum",
    cssFamily: '"WW Forum"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Шрифт с римскими пропорциями, торжественный и спокойный.",
  },
  {
    id: 'kelly-slab',
    label: "Kelly Slab",
    cssFamily: '"WW Kelly Slab"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Брусковый ретро-шрифт с вывесочным характером.",
  },
  {
    id: 'oranienbaum',
    label: "Oranienbaum",
    cssFamily: '"WW Oranienbaum"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Тонкая контрастная антиква для крупных заголовков.",
  },
  {
    id: 'playfair-display',
    label: "Playfair Display",
    cssFamily: '"WW Playfair Display"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400, 500, 700, 800],
    description: "Редакционная контрастная антиква для выразительных заголовков.",
  },
  {
    id: 'prata',
    label: "Prata",
    cssFamily: '"WW Prata"',
    category: 'display',
    source: 'hero',
    bodySafe: false,
    weights: [400],
    description: "Контрастный акцидентный шрифт для коротких заголовков.",
  },
  {
    id: 'rubik-distressed',
    label: "Rubik Distressed",
    cssFamily: '"WW Rubik Distressed"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Затёртая печать с выщербленным контуром.",
  },
  {
    id: 'rubik-glitch',
    label: "Rubik Glitch",
    cssFamily: '"WW Rubik Glitch"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Сбой изображения: буквы «рассыпаются» по пикселям.",
  },
  {
    id: 'rubik-iso',
    label: "Rubik Iso",
    cssFamily: '"WW Rubik Iso"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Объёмные изометрические буквы.",
  },
  {
    id: 'rubik-marker-hatch',
    label: "Rubik Marker Hatch",
    cssFamily: '"WW Rubik Marker Hatch"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Буквы, заштрихованные маркером от руки.",
  },
  {
    id: 'rubik-mono-one',
    label: "Rubik Mono One",
    cssFamily: '"WW Rubik Mono One"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Толстый моноширинный шрифт для плакатных цифр.",
  },
  {
    id: 'rubik-moonrocks',
    label: "Rubik Moonrocks",
    cssFamily: '"WW Rubik Moonrocks"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Пузырчатые лунные буквы, очень неформально.",
  },
  {
    id: 'rubik-puddles',
    label: "Rubik Puddles",
    cssFamily: '"WW Rubik Puddles"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Растёкшиеся буквы, как чернила по мокрой бумаге.",
  },
  {
    id: 'rubik-spray-paint',
    label: "Rubik Spray Paint",
    cssFamily: '"WW Rubik Spray Paint"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Трафарет из баллончика, уличный характер.",
  },
  {
    id: 'rubik-vinyl',
    label: "Rubik Vinyl",
    cssFamily: '"WW Rubik Vinyl"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Виниловая наклейка с толстым контуром.",
  },
  {
    id: 'rubik-wet-paint',
    label: "Rubik Wet Paint",
    cssFamily: '"WW Rubik Wet Paint"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Свежая краска с потёками.",
  },
  {
    id: 'ruslan-display',
    label: "Ruslan Display",
    cssFamily: '"WW Ruslan Display"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Древнерусская вязь для одного короткого слова.",
  },
  {
    id: 'seymour-one',
    label: "Seymour One",
    cssFamily: '"WW Seymour One"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Сверхжирный шрифт для одного слова во весь экран.",
  },
  {
    id: 'stalinist-one',
    label: "Stalinist One",
    cssFamily: '"WW Stalinist One"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Тяжёлый плакатный шрифт в стиле советской типографики.",
  },
  {
    id: 'tenor-sans',
    label: "Tenor Sans",
    cssFamily: '"WW Tenor Sans"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Элегантный заголовочный гротеск с журнальным настроением.",
  },
  {
    id: 'unbounded',
    label: "Unbounded",
    cssFamily: '"WW Unbounded"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400, 500, 700],
    description: "Широкий футуристичный шрифт для коротких сильных заголовков.",
  },
  {
    id: 'underdog',
    label: "Underdog",
    cssFamily: '"WW Underdog"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Гротеск с рваным контуром, будто напечатан на плохой бумаге.",
  },
  {
    id: 'yeseva-one',
    label: "Yeseva One",
    cssFamily: '"WW Yeseva One"',
    category: 'display',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Декоративная антиква с выразительной русской пластикой.",
  },
  {
    id: 'bad-script',
    label: "Bad Script",
    cssFamily: '"WW Bad Script"',
    category: 'handwritten',
    source: 'hero',
    bodySafe: false,
    weights: [400],
    description: "Мягкий рукописный шрифт с естественной кириллицей.",
  },
  {
    id: 'caveat',
    label: "Caveat",
    cssFamily: '"WW Caveat"',
    category: 'handwritten',
    source: 'hero',
    bodySafe: false,
    weights: [500, 600],
    description: "Живой рукописный акцент для коротких фраз.",
  },
  {
    id: 'lobster',
    label: "Lobster",
    cssFamily: '"WW Lobster"',
    category: 'handwritten',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Жирный вывесочный курсив, узнаваемый с одного взгляда.",
  },
  {
    id: 'marck-script',
    label: "Marck Script",
    cssFamily: '"WW Marck Script"',
    category: 'handwritten',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Плавный рукописный акцент с полноценной кириллицей.",
  },
  {
    id: 'neucha',
    label: "Neucha",
    cssFamily: '"WW Neucha"',
    category: 'handwritten',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Неформальный рукописный шрифт для живых заголовков.",
  },
  {
    id: 'pacifico',
    label: "Pacifico",
    cssFamily: '"WW Pacifico"',
    category: 'handwritten',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Расслабленный сёрф-курсив для тёплых заголовков.",
  },
  {
    id: 'pangolin',
    label: "Pangolin",
    cssFamily: '"WW Pangolin"',
    category: 'handwritten',
    source: 'library',
    bodySafe: false,
    weights: [400],
    description: "Дружелюбный рисованный шрифт для неформальных акцентов.",
  },
  {
    id: 'shantell-sans',
    label: "Shantell Sans",
    cssFamily: '"WW Shantell Sans"',
    category: 'handwritten',
    source: 'library',
    bodySafe: false,
    weights: [400, 500, 700],
    description: "Экспрессивный, но аккуратный рукописный шрифт.",
  },
] as const satisfies readonly ContentFontDefinition[];
